# 修改挂载文件后重新加载启动容器
# docker-compose up -d --force-recreate

version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./logs/redis:/logs
      - ./config/redis.conf:/etc/redis.conf:rw
    command: redis-server /etc/redis.conf

  mysql:
    image: "mysql:5.7"
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "summer2022"
      MYSQL_USER: "chao"
      MYSQL_PASSWORD: "summer2022"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./config/my.cnf:/etc/my.cnf:rw
      - ./init/mysql:/docker-entrypoint-initdb.d/

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     # - 8080:80
  #     # - 80:80
  #     - 81:81
  #     # - 443:443
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf:rw
  #     - ./config/nginx:/etc/nginx/conf.d
  #     - ./logs/nginx:/var/log/nginx
  #     - ./data/nginx/dist:/home/dist
