spring:
  datasource:
    username: chao
    password: mysql2020!
    url: jdbc:mysql://rock.chao.com:3306/summer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: rock.chao.com
    port: 6379
    timeout: 5000ms

  session:
    store-type: redis
    timeout: 36000s
    redis:
      flush-mode: on_save
      namespace: spring:session

  liquibase:
    enabled: false

  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1
    enabled: false
