spring:
  datasource:
    username: root
    password: summer2022
    url: jdbc:mysql://working.chao.com:3306/summer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat:监控统计、slf4j：日志记录、wall：防御sql注入
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: working.chao.com
    port: 6379
    timeout: 5000ms
    password: summer2022

  #  session:
  #    store-type: redis
  #    timeout: 6000s
  #    redis:
  #      flush-mode: on_save
  #      namespace: summer:session

  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #  mapper-locations: classpath*:mapper/*.xml

#logging:
#  file:
#    max-size: 128MB
#    path: C:\Workspace\log


#debug: true
