spring:
  datasource:
    username: chao
    password: summer2022
    url: jdbc:mysql://rock.chao.com:3306/summer?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: rock.chao.com
    port: 6379
    timeout: 5000ms
    password: summer2022

  #  session:
  #    store-type: redis
  #    timeout: 6000s
  #    redis:
  #      flush-mode: on_save
  #      namespace: summer:session

  flyway:
    baseline-on-migrate: true
    baseline-version: 0.1
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #  mapper-locations: classpath*:mapper/*.xml

#logging:
#  file:
#    max-size: 128MB
#    path: C:\Workspace\log


#debug: true
